name: ${pluginName}
main: uk.protonull.smithery.Smithery
author: Protonull
version: ${version}
description: ${description}
api-version: ${api_version}
depend: [CivModCore]
permissions:
  smithery.admin:
    default: op
  smithery.smelt:
    default: true
  smithery.cool:
    default: true
  smithery.checktime:
    default: true
  smithery.remove:
    default: true
  smithery.inspect:
    default: op